name: 'NuGet Push (nuget.org)'
on:
  workflow_call:
    inputs:
      artifact_name_in:
        description: 'Name of an artifact saved by a previous workflow'
        default: 'workflow-share'
        required: false
        type: string
    secrets:
      NUGET_API_KEY:
        required: true
        
jobs:
  nuget_push_github:
    name: 'Push .nupkg files to nuget.org'
    runs-on: ubuntu-latest
    steps:
      - name: Download source artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: ${{ inputs.artifact_name_in }}

      - name: Unzip artifact archive
        run: |
          7z x ${{ inputs.artifact_name_in }}.7z
          rm -f ${{ inputs.artifact_name_in }}.7z

      - name: Publish Nuget to GitHub registry
        run: dotnet nuget push **/*.nupkg --api-key $API_KEY --source https://api.nuget.org/v3/index.json
        env:
          API_KEY: ${{ secrets.NUGET_API_KEY }}
         