name: 'Tag & Release'
on:
  workflow_call:
    inputs:
      git_config_user_email:
        description: 'E-mail to put in git config user.email'
        required: true
        type: string
      git_config_user_name:
        description: 'E-mail to put in git config user.email'
        required: true
        type: string 
      git_tag:
        description: 'Git tag to create'
        required: true
        type: string
      changelog_builder_configuration:
        description: 'Relative path to the configuration.json file for the mikepenz/release-changelog-builder-action'
        required: true
        type: string
      release_artifacts:
        description: 'Set of paths representing artifacts to upload to the release' 
        required: true
        type: string
      artifact_name_in:
        description: 'Name of an artifact saved by a previous workflow'
        default: 'workflow-share'
        required: false
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true

jobs:
  release:
    name: 'Create Tag and Release'
    runs-on: ubuntu-latest
    steps:
      - name: Download source artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: ${{ inputs.artifact_name_in }}

      - name: Unzip artifact archive
        run: |
          7z x ${{ inputs.artifact_name_in }}.7z
          rm -f ${{ inputs.artifact_name_in }}.7z
                    
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}    
    
      - name: Create Tag
        run: |
          git remote set-url origin git@github.com:$REPOSITORY.git
          git config user.name "$USER_NAME"
          git config user.email "$EMAIL"
          git tag -a $TAG -m "$TAG"
          git push --follow-tags
        env:
          REPOSITORY: ${{ github.repository }}
          USER_NAME: ${{ inputs.git_config_user_name }}
          EMAIL: ${{ inputs.git_config_user_email }}
          TAG: ${{ inputs.git_tag }}

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3.5.0
        with:
          failOnError: true
          configuration: "${{ inputs.changelog_builder_configuration }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifactErrorsFailBuild: true
          draft: false
          body: "${{steps.build_changelog.outputs.changelog}}"
          tag: "${{ inputs.git_tag }}"
          artifacts: "${{ inputs.release_artifacts }}"
          token: ${{ secrets.GITHUB_TOKEN }}
